# Supports out of source build
# This BUILD_DIR is a default value which can be overridden when called from a Makefile generated by configure.sh
# If not called from an external Makefile generated by configure.sh, we will have a default build directory in ./build
BUILD_DIR := $(CURDIR)/build
SRC_DIR := $(CURDIR)
AR := ar
CPP := cpp
CC := gcc
CXX := g++

FLAGS +=
CFLAGS +=
CXXFLAGS += -std=c++20 -Werror
LDFLAGS +=
OBJECT_FLAGS := -c -I'$(SRC_DIR)' -I'$(SRC_DIR)'/external
OBJECT_CFLAGS :=
OBJECT_CXXFLAGS :=
EXECUTABLE_FLAGS := -fpie
SHARED_LIB_FLAGS := -fpic
STATIC_LIB_FLAGS := -fpic
OBJECT_LIB_FLAGS := -fpic
EXECUTABLE_LDFLAGS :=
SHARED_LIB_LDFLAGS := -shared
EXECUTABLE_OBJECT_CFLAGS :=
SHARED_LIB_OBJECT_CFLAGS :=
STATIC_LIB_OBJECT_CFLAGS :=
EXECUTABLE_OBJECT_CXXFLAGS := 
SHARED_LIB_OBJECT_CXXFLAGS := 
STATIC_LIB_OBJECT_CXXFLAGS := 

EXECUTABLE_TARGETS := 
SHARED_LIB_TARGETS :=
STATIC_LIB_TARGETS := 
# Use object lib if we just want to make a bunch of relocatable objects (.o) without any further linking/archiving.
# It is a simple way of categorising a bunch of object files we want to build. Useful for development purposes.
OBJECT_LIB_TARGETS := simulator assembler
PSEUDO_TARGETS := linenoise

simulator_PRIVATE_SOURCES := instruction.cpp register.cpp machine.cpp

assembler_PRIVATE_SOURCES := assembler.cpp

simulator_PRIVATE_DEPS := linenoise

linenoise_DIR := external/linenoise/

linenoise_INTERFACE_OBJECT_FLAGS := 

linenoise_INTERFACE_SOURCES := $(linenoise_DIR)/linenoise.c 

include $(CURDIR)/build_system.mk
